name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Staging the app!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your app.
